export const appConstants = {  
  REGISTER_STUDENT_REQUEST: "REGISTER_STUDENT_REQUEST",
  REGISTER_STUDENT_SUCCESS: "REGISTER_STUDENT_SUCCESS",
  REGISTER_STUDENT_FAILURE: "REGISTER_STUDENT_FAILURE",
  GET_APPLICATION_DETAILS_REQUEST: "GET_APPLICATION_DETAILS_REQUEST",
  GET_APPLICATION_DETAILS_SUCCESS: "GET_APPLICATION_DETAILS_SUCCESS",
  GET_APPLICATION_DETAILS_FAILURE: "GET_APPLICATION_DETAILS_FAILURE",
  SET_REDIRECT: "SET_REDIRECT",
  RESET_ERROR_AND_MESSAGE: "RESET_ERROR_AND_MESSAGE",
  RESET: "RESET",
}